BACKUP DATABASE [AdventureWorks2022] TO  DISK = N'C:\SQL_BACKUPS\AdventureWorks2022_diff_1.diff' WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'AdventureWorks2022-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
